services:
  db:
    image: postgres:15
    container_name: rag_and_roll_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tu_contrasena_aca
      POSTGRES_DB: rag_and_roll
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: